# Site settings
title:        Phuze
tagline:      "Internet Wizard."
description:  "Document all the things."
url:          https://phuze.dev
logo:         /assets/favicon.png
lang:         en

# Author
author:
  name:         Brendon LaRusic
  email:        brendon@larusic.ca
  url:          https://phuze.dev

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-spaceship
  - jekyll-toc
  - jekyll-gist
  - jemoji

# Permalinks
permalink:      /:title
paginate:       3

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: brendon@larusic.ca
  github: https://github.com/phuze
  linkedin: https://www.linkedin.com/in/brendon-larusic/

# Config for the spaceship plugin
# https://github.com/jeffreytse/jekyll-spaceship
jekyll-spaceship:
  processors:
    - table-processor